### ISSUE TITLE
Initial Website Setup Todo's

### ISSUE THREAD

**Issue by zacharycohn** [zacharycohn/Atomic82#1]
## To Do's
- [x] Content outline: what sections do we want to have? What topics do we want to cover?
- [x] Wireframe site - what layout/format could work well for each section? 
- [x] Write content
- [x] Create mailchimp account/wire it up
- [ ] Design mailchimp template/write basic "you signed up" email
- [x] Install Google Analytics
- [ ] Research and set up fb tracking pixels
- [ ] Zac - Check evernote "growth" tag and see if that inspires anything else

## Bugs
- [x] Menu too far to the right on mobile
- [ ] logo change
- [ ] remove extra slider icons
- [x] fix green underline spacing
- [x] fix www. bug
